version: '3.8'

services:
  bloglist-backend:
    image: bloglist-backend-dev
    build:
      context: ./backend/
      dockerfile: dev.Dockerfile
    volumes:
      - ./backend:/usr/src/app
  bloglist-frontend:
    image: bloglist-frontend-dev
    build:
      context: ./frontend/
      dockerfile: dev.Dockerfile
    environment:
      - VITE_BACKEND_URL=http://localhost:8080/api/
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8080:80
    depends_on:
      - bloglist-frontend